## Data Cleaning and Analysis for used cars from eBay.

In this project, we will clean and analysis the Data set of used car from eBayKleinanzeigen, a classifieds section of the German eBay website.

The dataset was originally scraped and uploaded to kaggle.

The data dictionary provided with data is as follows:

- dateCrawled - When this ad was first crawled. All field-values are taken from this date.
- name - Name of the car.
- seller - Whether the seller is private or a dealer.
- offerType - The type of listing
- price - The price on the ad to sell the car.
- abtest - Whether the listing is included in an A/B test.
- vehicleType - The vehicle Type.
- yearOfRegistration - The year in which the car was first registered.
- gearbox - The transmission type.
- powerPS - The power of the car in PS.
- model - The car model name.
- kilometer - How many kilometers the car has driven.
- monthOfRegistration - The month in which the car was first - registered.
- fuelType - What type of fuel the car uses.
- brand - The brand of the car.
- notRepairedDamage - If the car has a damage which is not yet repaired.
- dateCreated - The date on which the eBay listing was created.
- nrOfPictures - The number of pictures in the ad.
- postalCode - The postal code for the location of the vehicle.
- lastSeenOnline - When the crawler saw this ad last online.

In [1]:
# Let's import the libraries.
import pandas as pd
import numpy as np

# Reading Data set.

autos = pd.read_csv('autos.csv', encoding="Latin-1")

In [2]:
autos

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

## Lets know more about the Dataset.

In [3]:
# Getting infomtion about the dtypes.
autos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
dateCrawled            50000 non-null object
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

In [4]:
# Below are the columns with dtypes 'int64'

autos.dtypes[autos.dtypes == 'int64']

yearOfRegistration     int64
powerPS                int64
monthOfRegistration    int64
nrOfPictures           int64
postalCode             int64
dtype: object

In [5]:
# Below are the columns with dtypes 'object'

autos.dtypes[autos.dtypes != 'int64']

dateCrawled          object
name                 object
seller               object
offerType            object
price                object
abtest               object
vehicleType          object
gearbox              object
model                object
odometer             object
fuelType             object
brand                object
notRepairedDamage    object
dateCreated          object
lastSeen             object
dtype: object

In [6]:
autos.head()

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

From the above few rows of dataset we can clearly see that, columns like 'price', 'odometer' represent the numerical values.
But they are string type and need to change to dtypes "int". 

There is not consistancy in the column name. With similar text pattern and meaningful column name, data analysis will be much easier.

Some spelling mistake need to correct in columns like 'seller','greabox' and need to start columns with capital letter.

## Cleaning Column Names

Here, we will change following columns name from camelcase to snakecase:

- yearOfRegistration to registration_year

- monthOfRegistration to registration_month

- notRepairedDamage to unrepaired_damage

- dateCreated to ad_created

In [7]:
# Let's create the function that helps us changing column name.

def change_col_name(old_col_name, new_col_name):
    autos.rename({old_col_name : new_col_name}, axis=1, inplace=True)

In [8]:
data = {
    'yearOfRegistration' : 'registration_year',
    'monthOfRegistration' : 'registration_month',
    'notRepairedDamage' : 'unrepaired_damage',
    'dateCreated' : 'ad_created'
    }

for key,value in data.items():
    change_col_name(key, value)

In [9]:
autos.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'registration_year', 'gearbox', 'powerPS', 'model',
       'odometer', 'registration_month', 'fuelType', 'brand',
       'unrepaired_damage', 'ad_created', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

In [10]:
autos.head()

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,registration_year,gearbox,powerPS,model,odometer,registration_month,fuelType,brand,unrepaired_damage,ad_created,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

## Initial Exploration and Cleaning.

In [11]:
autos.describe(include='all')

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,registration_year,gearbox,powerPS,model,odometer,registration_month,fuelType,brand,unrepaired_damage,ad_created,nrOfPictures,postalCode,lastSeen
count,50000,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-03-10 15:36:24,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

In [12]:
# In below 'price' and 'odometer' columns. Numeric values is stored as a text. 
# we need to change it to dtypes as 'int'.
autos[['price','odometer']].head()

    price   odometer
0  $5,000  150,000km
1  $8,500  150,000km
2  $8,990   70,000km
3  $4,350   70,000km
4  $1,350  150,000km

In [13]:
# Correcting data and changing dtypes for column 'price'.
price = autos['price']
price_without_dollar = []

for each in price:
    if each.startswith('$'):
        result = each.replace('$', "")
        result = result.replace(',', "")
        price_without_dollar.append(result)
    else:
        each = each.replace(",", "")
        price_without_dollar.append(each)
        
autos['price'] = price_without_dollar
autos['price'] = autos['price'].astype(int)

In [14]:
autos['price'].head()

0    5000
1    8500
2    8990
3    4350
4    1350
Name: price, dtype: int64

In [15]:
# Correcting data and changing dtypes for column 'odometer'.

odometer = autos['odometer']
odometer_without_km = []

for each in odometer:
    if each.endswith('km'):
        result = each.replace('km', "")
        result = result.replace(',', "")
        odometer_without_km.append(result)
    else:
        each = each.replace(",", "")
        odometer_without_km.append(each)
        
autos['odometer'] = odometer_without_km
autos['odometer'] = autos['odometer'].astype(int)

In [16]:
autos['odometer'].head()

0    150000
1    150000
2     70000
3     70000
4    150000
Name: odometer, dtype: int64

In [17]:
# Passing values to function we have created to change the name of column.

change_col_name('odometer', 'odometer_km')

autos.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'registration_year', 'gearbox', 'powerPS', 'model',
       'odometer_km', 'registration_month', 'fuelType', 'brand',
       'unrepaired_damage', 'ad_created', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

In [18]:
# Lets see the what is higest and lower selling price for car
autos['price'].max()

99999999

In [19]:
autos['price'].min()

0

In [20]:
autos['price'].value_counts().sort_index(ascending=False)

99999999       1
27322222       1
12345678       3
11111111       2
10000000       1
3890000        1
1300000        1
1234566        1
999999         2
999990         1
350000         1
345000         1
299000         1
295000         1
265000         1
259000         1
250000         1
220000         1
198000         1
197000         1
194000         1
190000         1
180000         1
175000         1
169999         1
169000         1
163991         1
163500         1
155000         1
151990         1
            ...
66             1
65             5
60             9
59             1
55             2
50            49
49             4
47             1
45             4
40             6
35             1
30             7
29             1
25             5
20             4
18             1
17             3
15             2
14             1
13             2
12             3
11             2
10             7
9              1
8              1
5              2
3              1
2              3
1            156
0           1421
Name: price, Length: 2357, dtype: int64

In [21]:
# Lets see the what is higest and lower selling price for car

autos['odometer_km'].max()

150000

In [22]:
autos['odometer_km'].min()

5000

In [23]:
autos['odometer_km'].value_counts().sort_index(ascending=False)

150000    32424
125000     5170
100000     2169
90000      1757
80000      1436
70000      1230
60000      1164
50000      1027
40000       819
30000       789
20000       784
10000       264
5000        967
Name: odometer_km, dtype: int64

From the above observation, we can see that, price range for car starts from 0 - 99,999,999. Selling car on 0 - 99,999,999 is not correct. we will filter all cars that price range between 10,000 to 50,000, which seems more resonable.

odometer of cars seems resonable. so we change it.

In [24]:
autos.loc[autos['price'].between(10000, 50000)]

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,registration_year,gearbox,powerPS,model,odometer_km,registration_month,fuelType,brand,unrepaired_damage,ad_created,nrOfPictures,postalCode,lastSeen
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,18900,test,coupe,1982,automatik,203,NaN,80000,6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,41500,test,cabrio,2004,manuell,320,911,150000,4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,25450,control,cabrio,2015,manuell,184,cooper,10000,1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,48500,control,limousine,2014,automatik,306,5er,30000,12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
37,2016-03-23 16:47:46,Seat_Altea_XL_2.0_TDI_CR_DPF_Style,privat,Angebot,13800,test,bus,2012,manuell,140,altea,90000,2,diesel,seat,nein,2016-03-23 00:00:00,0,85113,2016-04-05 20:17:53
42,2016-03-22 21:37:03,Vw_Polo_l.0_/60_PS_Blue_Motion_Technologie_Son...,privat,Angebot,11900,control,kleinwagen,2014,manuell,60,polo,20000,7,benzin,volkswagen,NaN,2016-03-22 00:00:00,0,26629,2016-04-06 18:44:39
43,2016-03-08 16:51:22,Audi_A1_1.2_TFSI_Attraction_mit_Garantie,privat,Angebot,11500,test,kleinwagen,2011,manuell,86,a1,60000,9,benzin,audi,nein,2016-03-08 00:00:00,0,85049,2016-04-07 03:16:05
63,2016-03-14 22:51:19,MINI_Mini_Cooper_S___Xenon_Leder,privat,Angebot,13950,control,kleinwagen,2011,manuell,184,cooper,70000,6,benzin,mini,nein,2016-03-14 00:00:00,0,14532,2016-04-06 18:46:08
68,2016-04-03 17:36:59,Mini_cooper_s_clubman_/vollausstattung_/_Navi/...,privat,Angebot,10990,test,NaN,2017,manuell,174,clubman,100000,0,NaN,mini,nein,2016-04-03 00:00:00,0,83135,2016-04-05 17:26:26
76,2016-03-22 14:52:57,BMW_318i_neustes_Model_0Km,privat,Angebot,31999,control,limousine,2016,manuell,136,3er,5000,2,benzin,bmw,NaN,2016-03-22 00:00:00,0,45149,2016-04-06 05:15:42
90,2016-03-07 13:50:22,Audi_A3_2.0_TDI_Cabrio_S_tronic__clean_diesel_...,privat,Angebot,34900,control,cabrio,2014,automatik,150,a3,20000,5,diesel,audi,nein,2016-03-07 00:00:00,0,32052,2016-03-24 03:47:03
95,2016-03-30 15:59:17,Jaguar_XJ_5.0_V8_Portfolio,privat,Angebot,36000,test,limousine,2012,automatik,385,andere,40000,8,benzin,jaguar,nein,2016-03-30 00:00:00,0,21720,2016-04-07 06:44:54
98,2016-04-04 15:47:36,Audi_A4_Cabriolet_2.0_TFSI_S_Line,privat,Angebot,13500,test,cabrio,2008,automatik,200,a4,125000,5,benzin,audi,NaN,2016-04-04 00:00:00,0,66459,2016-04-06 17:17:56
104,2016-03-12 12:57:24,Volkswagen_Multivan_T4_TDI_Highline,privat,Angebot,12000,test,bus,2001,manuell,151,transporter,150000,7,diesel,volkswagen,nein,2016-03-12 00:00:00,0,16540,2016-03-24 04:20:05
105,2016-04-05 00:36:24,BMW_525d_Aut.,privat,Angebot,20999,control,limousine,2011,automatik,204,5er,150000,6,diesel,bmw,nein,2016-04-05 00:00:00,0,59348,2016-04-07 11:15:41
114,2016-03-23 17:51:11,Volkswagen_Passat_Variant_2.0_TDI_BlueMotion_T...,privat,Angebot,18700,control,kombi,2013,manuell,140,passat,60000,11,diesel,volkswagen,nein,2016-03-23 00:00:00,0,38440,2016-04-05 22:17:49
120,2016-03-24 22:56:04,Golf_VII_1_4_TSI_Highline_Autom_Panorama_Alcan...,privat,Angebot,18900,control,limousine,2013,automatik,122,golf,30000,7,benzin,volkswagen,nein,2016-03-24 00:00:00,0,58708,2016-03-31 11:15:33
131,2016-04-03 14:49:09,Audi_A3_Sportback,privat,Angebot,11900,test,limousine,2009,manuell,160,a3,100000,12,benzin,audi,nein,2016-04-03 00:00:00,0,56727,2016-04-03 14:49:09
133,2016-03-20 02:02:00,Mercedes_Benz_ML_270_CDI_Final_Edition,privat,Angebot,10000,test,suv,2005,automatik,163,m_klasse,150000,9,diesel,mercedes_benz,nein,2016-03-20 00:00:00,0,55758,2016-04-06 02:46:54
134,2016-03-10 21:37:02,Mercedes_E200_kompressor,privat,Angebot,32000,control,limousine,2008,automatik,183,e_klasse,70000,9,benzin,mercedes_benz,nein,2016-03-10 00:00:00,0,34270,2016-04-07 00:17:11
138,2016-03-10 13:49:35,Ford_C_Max_Titanium_1_0L._125Ps_Benziner__Magn...,privat,Angebot,18300,test,bus,2015,manuell,125,c_max,20000,7,benzin,ford,NaN,2016-03-10 00:00:00,0,66571,2016-03-23 10:17:21
139,2016-03-13 19:43:32,Mercedes_Benz_E_320,privat,Angebot,11490,control,limousine,2003,automatik,0,e_klasse,125000,10,benzin,mercedes_benz,NaN,2016-03-13 00:00:00,0,64283,2016-03-31 22:45:11
142,2016-04-01 00:46:44,Audi_A4_Avant_2.0_TDI_quattro_S_tronic__S_Line...,privat,Angebot,29950,test,kombi,2013,automatik,177,a4,50000,3,diesel,audi,nein,2016-03-31 00:00:00,0,85049,2016-04-07 02:44:24
153,2016-03-24 10:52:19,Porsche_Porsche_968___Turbo_S_Optik__Speed_Lin...,privat,Angebot,31000,test,coupe,1992,manuell,239,andere,150000,3,benzin,porsche,nein,2016-03-24 00:00:00,0,63517,2016-04-07 01:46:56
155,2016-03-07 18:45:47,VW_Touran__140_PS,privat,Angebot,23900,control,bus,2012,automatik,0,touran,30000,8,benzin,volkswagen,NaN,2016-03-07 00:00:00,0,85080,2016-04-07 03:15:35
157,2016-03-25 00:56:03,Mercedes_Benz_C_200_T_CDI_DPF_BlueEFFICIENCY_A...,privat,Angebot,12400,control,kombi,2010,manuell,136,c_klasse,150000,2,diesel,mercedes_benz,nein,2016-03-24 00:00:00,0,44651,2016-04-06 06:17:21
159,2016-03-22 21:56:30,Mini_Cooper_S__Leder__Xenon__Navi__Harman_Kard...,privat,Angebot,18800,control,kleinwagen,2013,manuell,184,cooper,30000,3,benzin,mini,nein,2016-03-22 00:00:00,0,70736,2016-04-02 17:46:49
161,2016-03-30 21:54:12,Volkswagen_Touareg_3.0_V6_TDI_DPF,privat,Angebot,11000,test,suv,2008,manuell,239,touareg,150000,7,diesel,volkswagen,ja,2016-03-30 00:00:00,0,57462,2016-04-05 13:16:08
165,2016-03-27 12:53:58,Audi_A4_2.0_TDI_S_line_Xenon_Alarmanlage,privat,Angebot,13950,test,limousine,2008,manuell,143,a4,125000,7,diesel,audi,nein,2016-03-27 00:00:00,0,56288,2016-03-30 16:16:33
166,2016-04-03 20:50:55,Mercedes_Benz_200/8,privat,Angebot,15000,test,limousine,1972,manuell,95,andere,80000,5,benzin,mercedes_benz,nein,2016-04-03 00:00:00,0,71032,2016-04-05 21:46:55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49822,2016-03-20 23:44:38,Mercedes_Benz_C_55_T_AMG_Automatik_V_MAX_offen...,privat,Angebot,14850,control,kombi,2004,automatik,367,c_klasse,150000,4,benzin,mercedes_benz,nein,2016-03-20 00:00:00,0,2692,2016-04-07 09:45:29
49832,2016-03-28 13:41:35,Hyundai_Santa_Fe_2.2_CRDi_/_Diesel__Automatik_...,privat,Angebot,29999,test,suv,2015,automatik,197,santa,20000,4,diesel,hyundai,nein,2016-03-28 00:00:00,0,50389,2016-04-04 15:18:15
49833,2016-03-23 07:58:17,Mercedes_SL_320_Liebhaber_Fahrzeug___Bordcompu...,privat,Angebot,13500,control,cabrio,1994,automatik,231,sl,150000,6,benzin,mercedes_benz,nein,2016-03-23 00:00:00,0,86415,2016-04-07 08:17:28
49840,2016-03-07 20:41:52,BMW_118d_DPF_M_Sportpaket,privat,Angebot,10990,test,limousine,2009,manuell,143,1er,125000,1,diesel,bmw,nein,2016-03-07 00:00:00,0,72669,2016-03-15 07:45:26
49842,2016-04-02 14:42:45,Mercedes_Benz_Vito_111_CDI_Kompakt,privat,Angebot,12500,test,bus,2009,NaN,0,vito,90000,1,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,30826,2016-04-06 12:46:12
49844,2016-03-26 19:43:51,Fahrzeug_Ankauf!!!!,privat,Angebot,22222,control,NaN,2005,NaN,0,NaN,5000,0,NaN,opel,NaN,2016-03-26 00:00:00,0,72160,2016-03-26 19:43:51
49847,2016-04-03 22:58:18,Volkswagen_Golf_1.4_TSI_BlueMotion_Technology_...,privat,Angebot,17499,control,limousine,2013,automatik,140,golf,40000,6,benzin,volkswagen,nein,2016-04-03 00:00:00,0,71665,2016-04-06 00:45:08
49853,2016-03-05 19:53:59,BMW_X3_2.0d,privat,Angebot,13500,test,limousine,2008,manuell,177,x_reihe,125000,3,diesel,bmw,nein,2016-03-05 00:00:00,0,81927,2016-04-03 18:16:38
49855,2016-03-24 09:36:21,Porsche_Cayman_S_PDK__Chrono_Plus__Approved__P...,privat,Angebot,33500,control,coupe,2009,automatik,320,andere,90000,1,benzin,porsche,nein,2016-03-24 00:00:00,0,74321,2016-03-24 09:36:21
49857,2016-03-21 17:40:01,Volkswagen_Golf_1.6_TDI_BlueMotion_Technology_...,privat,Angebot,16490,control,limousine,2013,manuell,105,golf,70000,2,diesel,volkswagen,nein,2016-03-21 00:00:00,0,27798,2016-04-06 17:46:46
49858,2016-03-14 14:45:47,Mercedes_Benz_Viano_3.0_CDI_lang_Automatik_Tre...,privat,Angebot,14990,control,bus,2008,automatik,204,viano,150000,4,diesel,mercedes_benz,nein,2016-03-14 00:00:00,0,34246,2016-04-05 16:47:18
49876,2016-03-22 17:57:24,Audi_a5_3.0_tdi_s_line,privat,Angebot,14700,control,NaN,2016,manuell,0,NaN,150000,10,diesel,audi,NaN,2016-03-22 00:00:00,0,44227,2016-03-22 18:40:53
49893,2016-03-15 13:58:31,Mitsubishi_Pajero_3.2_DI_D_Automatik_Instyle,privat,Angebot,19500,control,suv,2007,automatik,170,pajero,60000,6,diesel,mitsubishi,nein,2016-03-15 00:00:00,0,91522,2016-03-22 15:17:52
49900,2016-03-26 13:56:07,Mercedes_Benz_S_350_CDI_4Matic_DPF_7G_TRONIC_B...,privat,Angebot,34990,control,limousine,2010,automatik,235,s_klasse,125000,6,diesel,mercedes_benz,nein,2016-03-26 00:00:00,0,63071,2016-04-06 01:47:06
49910,2016-04-03 21:39:15,Schoener_fast_neuer_Opel_Mokka_in_Zell_Mosel_m...,privat,Angebot,22200,test,NaN,9000,automatik,140,andere,10000,3,benzin,opel,NaN,2016-04-03 00:00:00,0,56856,2016-04-05 22:18:26
49911,2016-04-02 07:54:30,BMW_X3_Euro4_TÃœV_Neu_Klima_Leder_AHK_Panorama_...,privat,Angebot,11500,test,suv,2007,manuell,0,x_reihe,150000,5,diesel,bmw,nein,2016-04-02 00:00:00,0,51588,2016-04-06 05:44:50
49939,2016-03-13 15:43:19,Audi_TT_Roadster_2.0_TFSI,privat,Angebot,16995,test,cabrio,2007,manuell,200,tt,80000,3,benzin,audi,nein,2016-03-13 00:00:00,0,94522,2016-04-06 17:16:35
49942,2016-03-09 19:43:33,Audi_A3_2.0_TDI_Sportback_DPF_Ambition,privat,Angebot,10000,test,kombi,2007,manuell,140,a3,125000,10,diesel,audi,nein,2016-03-09 00:00:00,0,66663,2016-04-05 13:15:31
49947,2016-03-28 11:44:30,Audi_A5_2.7_TDI_+S_Line_Vollausstattung/ABT/B&...,privat,Angebot,23600,control,coupe,2009,automatik,190,a5,150000,3,diesel,audi,nein,2016-03-28 00:00:00,0,74889,2016-04-06 13:44:59
49948,2016-03-22 16:44:57,Hyundai_ix35_2.0_CRDi_4WD_Automatik,privat,Angebot,19900,test,suv,2013,automatik,184,i_reihe,70000,5,diesel,hyundai,nein,2016-03-22 00:00:00,0,96515,2016-04-06 06:45:11
49953,2016-03-30 17:55:21,Ford_Mustang,privat,Angebot,14750,control,coupe,1967,automatik,163,mustang,125000,8,benzin,ford,nein,2016-03-30 00:00:00,0,84478,2016-03-30 17:55:21
49964,2016-03-10 16:46:43,Audi_2_7_TDI_AVANT,privat,Angebot,12700,control,kombi,2010,automatik,192,a4,150000,5,diesel,audi,NaN,2016-03-10 00:00:00,0,54441,2016-04-07 01:15:47
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,15800,control,bus,2010,automatik,136,c4,60000,4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,11000,test,kleinwagen,2011,manuell,90,polo,70000,11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,15900,control,limousine,2010,automatik,218,300c,125000,11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,21990,control,limousine,2013,manuell,150,a3,50000,11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,17500,test,limousine,2012,manuell,156,a_klasse,30000,12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,24900,control,limousine,2011,automatik,239,q5,100000,1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,13200,test,cabrio,2014,automatik,69,500,5000,11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,22900,control,kombi,2013,manuell,150,a3,40000,11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07

## Working with Date columns

In [25]:
autos[['dateCrawled','ad_created','lastSeen','registration_year']].head()

,dateCrawled,ad_created,lastSeen,registration_year
0,2016-03-26 17:47:46,2016-03-26 00:00:00,2016-04-06 06:45:54,2004
1,2016-04-04 13:38:56,2016-04-04 00:00:00,2016-04-06 14:45:08,1997
2,2016-03-26 18:57:24,2016-03-26 00:00:00,2016-04-06 20:15:37,2009
3,2016-03-12 16:58:10,2016-03-12 00:00:00,2016-03-15 03:16:28,2007
4,2016-04-01 14:38:50,2016-04-01 00:00:00,2016-04-01 14:38:50,2003

In [26]:
# Top five Crawling Date.
autos['dateCrawled'].str.split().str[0].value_counts().head()

2016-04-03    1934
2016-03-20    1891
2016-03-21    1876
2016-03-12    1839
2016-03-14    1831
Name: dateCrawled, dtype: int64

In [27]:
# Top five ad Created Date.
autos['ad_created'].str.split().str[0].value_counts().head()

2016-04-03    1946
2016-03-20    1893
2016-03-21    1886
2016-04-04    1844
2016-03-12    1831
Name: ad_created, dtype: int64

In [28]:
# Let find in which year maximum car has registerd.
autos['registration_year'].isnull().sum()

autos['registration_year'].value_counts().head()

2000    3354
2005    3015
1999    3000
2004    2737
2003    2727
Name: registration_year, dtype: int64

In Year 2000, 3354 cars has registered.

In [29]:
# Lets find how many number of car has registed in last five year.
autos['registration_year'].value_counts().sort_values(ascending=False).head()

2000    3354
2005    3015
1999    3000
2004    2737
2003    2727
Name: registration_year, dtype: int64

In [30]:
autos.loc[autos['registration_year'].between(1900, 2016)][:5]

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,registration_year,gearbox,powerPS,model,odometer_km,registration_month,fuelType,brand,unrepaired_damage,ad_created,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,5000,control,bus,2004,manuell,158,andere,150000,3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,8500,control,limousine,1997,automatik,286,7er,150000,6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,8990,test,limousine,2009,manuell,102,golf,70000,7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,4350,control,kleinwagen,2007,automatik,71,fortwo,70000,6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,1350,test,kombi,2003,manuell,0,focus,150000,7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

## Exploring Price by Brand

In [61]:
# Car sold by Brand
autos['brand'].value_counts(normalize=True)

volkswagen        0.21374
opel              0.10922
bmw               0.10858
mercedes_benz     0.09468
audi              0.08566
ford              0.06958
renault           0.04808
peugeot           0.02912
fiat              0.02616
seat              0.01882
skoda             0.01572
mazda             0.01514
nissan            0.01508
smart             0.01402
citroen           0.01402
toyota            0.01234
sonstige_autos    0.01092
hyundai           0.00976
volvo             0.00914
mini              0.00848
mitsubishi        0.00812
honda             0.00798
kia               0.00712
alfa_romeo        0.00658
porsche           0.00588
suzuki            0.00586
chevrolet         0.00566
chrysler          0.00362
dacia             0.00258
daihatsu          0.00256
jeep              0.00220
subaru            0.00218
land_rover        0.00198
saab              0.00160
daewoo            0.00158
trabant           0.00156
jaguar            0.00154
rover             0.00138
lancia            0.00114
lada              0.00062
Name: brand, dtype: float64

In [66]:
brand_counts = autos["brand"].value_counts(normalize=True)
common_brands = brand_counts[brand_counts > .05].index
print(common_brands)

Index(['volkswagen', 'opel', 'bmw', 'mercedes_benz', 'audi', 'ford'], dtype='object')

In [69]:
brand_mean_prices = {}

for brand in common_brands:
    brand_only = autos[autos["brand"] == brand]
    mean_price = brand_only["price"].mean()
    brand_mean_prices[brand] = int(mean_price)

brand_mean_prices

{'audi': 8965,
 'bmw': 8252,
 'ford': 7105,
 'mercedes_benz': 29511,
 'opel': 5106,
 'volkswagen': 6384}

We can see that,
    - Audi, BMW, and Mercedes Benz are most expensive.
    - ford and volkswagen are mid range.
    - opel in less expensive.

## Finding the most common brand/model combinations.

In [94]:
brand_model = {}

for brand in common_brands:
    brand_model[brand] = len(autos.loc[autos['brand']==brand]['model'].unique())
    
brand_model

{'audi': 17,
 'bmw': 11,
 'ford': 15,
 'mercedes_benz': 19,
 'opel': 17,
 'volkswagen': 23}

Volkswagen has 23 models of cars followed by:
    - mercedes benz : 19
    - audi and opel : 17
    - ford : 15
    - bmw : 11